classifier:
  name: FEN_SISR_loss_parser_withholding_flickr2k
  train:
    learning_rate: 0.0001
    num_epochs: 2
  type: FEN
evaluation_datasets:
- include_custom_trained: true
  include_pretrained: true
  label_param: loss
  name: SISR_loss_parser_test
  random_crop: false
  type: SISR
training_dataset:
  include_custom_trained: true
  include_pretrained: false
  label_param: loss
  name: SISR_loss_parser_withholding_flickr2k_train_center_crop
  random_crop: false
  reserved_param: dataset
  reserved_param_value: flickr2k
  type: SISR
validation_dataset:
  include_custom_trained: true
  include_pretrained: false
  label_param: loss
  name: SISR_loss_parser_withholding_flickr2k_val
  random_crop: false
  reserved_param: dataset
  reserved_param_value: flickr2k
  type: SISR
