classifier:
  name: FEN_SISR_scale_parser_withholding_RCAN
  train:
    learning_rate: 0.0001
    num_epochs: 2
  type: FEN
evaluation_datasets:
- include_custom_trained: true
  include_pretrained: true
  label_param: scale
  name: SISR_scale_parser_test
  random_crop: false
  type: SISR
training_dataset:
  include_custom_trained: true
  include_pretrained: false
  label_param: scale
  name: SISR_scale_parser_withholding_RCAN_train_center_crop
  random_crop: false
  reserved_param: architecture
  reserved_param_value: RCAN
  type: SISR
validation_dataset:
  include_custom_trained: true
  include_pretrained: false
  label_param: scale
  name: SISR_scale_parser_withholding_RCAN_val
  random_crop: false
  reserved_param: architecture
  reserved_param_value: RCAN
  type: SISR
