classifier:
  name: FEN_SISR_architecture_parser_withholding_3
  train:
    learning_rate: 0.0001
    num_epochs: 2
  type: FEN
evaluation_datasets:
- include_custom_trained: true
  include_pretrained: true
  label_param: architecture
  name: SISR_architecture_parser_test
  random_crop: false
  type: SISR
training_dataset:
  include_custom_trained: true
  include_pretrained: false
  label_param: architecture
  name: SISR_architecture_parser_withholding_3_train_center_crop
  random_crop: false
  reserved_param: seed
  reserved_param_value: 3
  type: SISR
validation_dataset:
  include_custom_trained: true
  include_pretrained: false
  label_param: architecture
  name: SISR_architecture_parser_withholding_3_val
  random_crop: false
  reserved_param: seed
  reserved_param_value: 3
  type: SISR
