python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_architecture_parser_withholding_3.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_architecture_parser_withholding_flickr2k.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_architecture_parser_withholding_L1.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_architecture_parser_withholding_VGG_GAN.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_dataset_parser_withholding_flickr2k.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_dataset_parser_withholding_L1.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_dataset_parser_withholding_RCAN.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_dataset_parser_withholding_SwinIR.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_dataset_parser_withholding_VGG.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_loss_parser_withholding_3.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_loss_parser_withholding_flickr2k.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_loss_parser_withholding_RCAN.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_loss_parser_withholding_SwinIR.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_3.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_flickr2k.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_L1.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_RCAN.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_SwinIR.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_VGG.yaml --mode test
python classification/train_classifier.py -opt classification/options/parsers/ConvNext_CNN_SISR_scale_parser_withholding_VGG_GAN.yaml --mode test