python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_architecture_parser_withholding_3.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_architecture_parser_withholding_flickr2k.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_architecture_parser_withholding_L1.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_architecture_parser_withholding_VGG_GAN.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_architecture_parser.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_dataset_parser_withholding_3.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_dataset_parser_withholding_flickr2k.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_dataset_parser_withholding_L1.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_dataset_parser_withholding_RCAN.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_dataset_parser_withholding_SwinIR.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_dataset_parser_withholding_VGG_GAN.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_loss_parser_withholding_3.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_loss_parser_withholding_flickr2k.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_loss_parser_withholding_RCAN.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_loss_parser_withholding_SwinIR.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_loss_parser.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser_withholding_3.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser_withholding_flickr2k.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser_withholding_L1.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser_withholding_RCAN.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser_withholding_SwinIR.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser_withholding_VGG_GAN.yaml --mode train
python classification/train_classifier.py -opt classification/options/parsers/PRNU_SISR_scale_parser.yaml --mode train

