AccForDiv: '95.8'
AccForDivMean: '96.1'
AccForDivStd: '1.0'
AccForEDSR: '95.8'
AccForEDSRMean: '94.9'
AccForEDSRStd: '1.3'
AccForFlickr: '96.7'
AccForFlickrMean: '96.6'
AccForFlickrStd: '0.1'
AccForFourX: '96.6'
AccForFourXMean: '96.6'
AccForFourXStd: '0.4'
AccForLOne: '89.4'
AccForLOneMean: '89.2'
AccForLOneStd: '1.5'
AccForNLSN: '95.7'
AccForNLSNMean: '96.1'
AccForNLSNStd: '0.9'
AccForQuarterDiv: '94.7'
AccForQuarterDivMean: '94.9'
AccForQuarterDivStd: '0.5'
AccForQuarterFlickr: '96.8'
AccForQuarterFlickrMean: '96.3'
AccForQuarterFlickrStd: '0.4'
AccForRCAN: '93.2'
AccForRCANMean: '94.7'
AccForRCANStd: '1.1'
AccForRDN: '96.9'
AccForRDNMean: '96.3'
AccForRDNStd: '0.5'
AccForResNet: '99.5'
AccForResNetMean: '99.6'
AccForResNetStd: '0.1'
AccForSwinIR: '98.1'
AccForSwinIRMean: '98.0'
AccForSwinIRStd: '0.4'
AccForTwoX: '95.3'
AccForTwoXMean: '95.4'
AccForTwoXStd: '0.7'
AccForVGG: '98.9'
AccForVGGMean: '99.2'
AccForVGGStd: '0.2'
ConvNextAcc: '94.9'
DistinctionBetweenSeedAcc: '98.8'
DistinctionBetweenSeedAccMean: '98.6'
DistinctionBetweenSeedAccStd: '0.2'
DistinctionBetweenSeedFourXLOneAcc: '97.1'
DistinctionBetweenSeedFourXLOneAccMean: '96.8'
DistinctionBetweenSeedFourXLOneAccStd: '0.4'
DistinctionBetweenSeedFourXResNetAcc: '100.0'
DistinctionBetweenSeedFourXResNetAccMean: '100.0'
DistinctionBetweenSeedFourXResNetAccStd: '0.0'
DistinctionBetweenSeedFourXVGGAcc: '100.0'
DistinctionBetweenSeedFourXVGGAccMean: '99.9'
DistinctionBetweenSeedFourXVGGAccStd: '0.0'
DistinctionBetweenSeedTwoXLOneAcc: '96.1'
DistinctionBetweenSeedTwoXLOneAccMean: '95.6'
DistinctionBetweenSeedTwoXLOneAccStd: '1.1'
DistinctionBetweenSeedTwoXResNetAcc: '99.7'
DistinctionBetweenSeedTwoXResNetAccMean: '99.8'
DistinctionBetweenSeedTwoXResNetAccStd: '0.1'
DistinctionBetweenSeedTwoXVGGAcc: '99.8'
DistinctionBetweenSeedTwoXVGGAccMean: '99.7'
DistinctionBetweenSeedTwoXVGGAccStd: '0.1'
EfficientNetAcc: '92.9'
LossAccRange: '9.8'
LossAccRangeMean: '10.2'
LossAccRangeStd: '1.5'
PRNUAccForDiv: '14.5'
PRNUAccForEDSR: '10.4'
PRNUAccForFlickr: '13.0'
PRNUAccForFourX: '19.0'
PRNUAccForLOne: '35.6'
PRNUAccForNLSN: '11.2'
PRNUAccForQuarterDiv: '13.5'
PRNUAccForQuarterFlickr: '14.4'
PRNUAccForRCAN: '13.8'
PRNUAccForRDN: '20.8'
PRNUAccForResNet: '1.9'
PRNUAccForSwinIR: '13.9'
PRNUAccForTwoX: '9.1'
PRNUAccForVGG: '4.6'
PRNUDistinctionBetweenSeedAcc: '62.2'
PRNUDistinctionBetweenSeedFourXLOneAcc: '81.3'
PRNUDistinctionBetweenSeedFourXResNetAcc: '46.8'
PRNUDistinctionBetweenSeedFourXVGGAcc: '46.2'
PRNUDistinctionBetweenSeedTwoXLOneAcc: '82.8'
PRNUDistinctionBetweenSeedTwoXResNetAcc: '45.4'
PRNUDistinctionBetweenSeedTwoXVGGAcc: '70.5'
PRNULossAccRange: '-32.4'
PRNUPreTrainedFourXLOneModelClassifierAcc: '20.3'
PRNUPreTrainedGANModelClassifierAcc: '7.3'
PRNUPreTrainedTwoXModelClassifierAcc: '0.9'
PRNUPretrainedClassifierAcc: '10.4'
PRNURCANSplitFourXDatasetParsingAccuracy: '23.6'
PRNURCANSplitFullDatasetParsingAccuracy: '33.8'
PRNURCANSplitLOneDatasetParsingAccuracy: '23.8'
PRNURCANSplitQuarterDatasetParsingAccuracy: '15.2'
PRNURCANSplitResNetDatasetParsingAccuracy: '24.8'
PRNURCANSplitTwoXDatasetParsingAccuracy: '25.4'
PRNURCANSplitVGGDatasetParsingAccuracy: '25.0'
PRNUScaleAccRange: '9.9'
PRNUScaleParsingHigh: '51.5'
PRNUScaleParsingLow: '49.5'
PRNUSwinIRSplitFourXLossParsingAccuracy: '31.1'
PRNUSwinIRSplitLoneLossParsingAccuracy: '32.4'
PRNUSwinIRSplitResNetLossParsingAccuracy: '35.4'
PRNUSwinIRSplitTwoXLossParsingAccuracy: '34.4'
PRNUSwinIRSplitVGGLossParsingAccuracy: '30.5'
PRNUThreeSplitFourXArchitectureParsingAccuracy: '21.9'
PRNUThreeSplitLOneArchitectureParsingAccuracy: '20.8'
PRNUThreeSplitResNetArchitectureParsingAccuracy: '20.3'
PRNUThreeSplitTwoXArchitectureParsingAccuracy: '17.7'
PRNUThreeSplitVGGArchitectureParsingAccuracy: '18.3'
PRNUVGGSplitFourXArchitectureParsingAccuracy: '20.2'
PRNUVGGSplitTwoXArchitectureParsingAccuracy: '20.2'
PRNUarchitectureWithholdingFlickr: '19.4'
PRNUarchitectureWithholdingLOne: '20.0'
PRNUarchitectureWithholdingVGG: '20.2'
PRNUarchitectureWithholdingthree: '19.8'
PRNUdatasetWithholdingLOne: '24.6'
PRNUdatasetWithholdingRCAN: '24.5'
PRNUdatasetWithholdingSwinIR: '24.8'
PRNUdatasetWithholdingVGG: '25.3'
PRNUlossWithholdingFlickr: '34.1'
PRNUlossWithholdingRCAN: '33.5'
PRNUlossWithholdingSwinIR: '32.8'
PRNUlossWithholdingthree: '34.9'
PRNUscaleWithholdingFlickr: '49.6'
PRNUscaleWithholdingLOne: '53.1'
PRNUscaleWithholdingRCAN: '49.6'
PRNUscaleWithholdingSwinIR: '51.5'
PRNUscaleWithholdingVGG: '50.9'
PRNUscaleWithholdingthree: '49.5'
PreTrainedFourXLOneModelClassifierAcc: '88.8'
PreTrainedFourXLOneModelClassifierAccMean: '87.9'
PreTrainedFourXLOneModelClassifierAccStd: '1.0'
PreTrainedGANModelClassifierAcc: '98.9'
PreTrainedGANModelClassifierAccMean: '98.7'
PreTrainedGANModelClassifierAccStd: '0.4'
PreTrainedTwoXModelClassifierAcc: '74.8'
PreTrainedTwoXModelClassifierAccMean: '77.4'
PreTrainedTwoXModelClassifierAccStd: '2.2'
PretrainedArchParsingAccuracy: '23.4'
PretrainedArchParsingAccuracyMean: '22.8'
PretrainedArchParsingAccuracyStd: '0.4'
PretrainedClassifierAcc: '87.1'
PretrainedClassifierAccMean: '87.5'
PretrainedClassifierAccStd: '0.6'
RCANSplitFourXDatasetParsingAccuracy: '45.5'
RCANSplitFullDatasetParsingAccuracy: '47.7'
RCANSplitLOneDatasetParsingAccuracy: '34.9'
RCANSplitQuarterDatasetParsingAccuracy: '25.6'
RCANSplitResNetDatasetParsingAccuracy: '34.9'
RCANSplitTwoXDatasetParsingAccuracy: '27.8'
RCANSplitVGGDatasetParsingAccuracy: '40.1'
ResnetAcc: '81.8'
ScaleAccRange: '1.3'
ScaleAccRangeMean: '1.2'
ScaleAccRangeStd: '0.2'
ScaleParsingHigh: '100.0'
ScaleParsingHighMean: '100.0'
ScaleParsingHighStd: '0.0'
ScaleParsingLow: '99.2'
ScaleParsingLowMean: '98.8'
ScaleParsingLowStd: '0.3'
SwinIRSplitFourXLossParsingAccuracy: '92.5'
SwinIRSplitLoneLossParsingAccuracy: '100.0'
SwinIRSplitResNetLossParsingAccuracy: '94.8'
SwinIRSplitTwoXLossParsingAccuracy: '96.2'
SwinIRSplitVGGLossParsingAccuracy: '88.2'
ThreeSplitFourXArchitectureParsingAccuracy: '73.5'
ThreeSplitLOneArchitectureParsingAccuracy: '76.0'
ThreeSplitResNetArchitectureParsingAccuracy: '68.0'
ThreeSplitTwoXArchitectureParsingAccuracy: '71.4'
ThreeSplitVGGArchitectureParsingAccuracy: '73.3'
VGGSplitFourXArchitectureParsingAccuracy: '52.9'
VGGSplitTwoXArchitectureParsingAccuracy: '38.1'
XceptionAcc: '93.2'
advarchitectureWithholdingFlickr: '73.2'
advarchitectureWithholdingVGG: '45.5'
advarchitectureWithholdingthree: '70.7'
advdatasetWithholdingFlickr: '0.0'
advdatasetWithholdingRCAN: '37.5'
advdatasetWithholdingSwinIR: '36.8'
advdatasetWithholdingVGG: '31.5'
advlossWithholdingFlickr: '98.0'
advlossWithholdingRCAN: '92.3'
advlossWithholdingSwinIR: '91.5'
advlossWithholdingthree: '98.2'
advscaleWithholdingFlickr: '100.0'
advscaleWithholdingRCAN: '99.0'
advscaleWithholdingSwinIR: '98.8'
advscaleWithholdingVGG: '99.4'
advscaleWithholdingthree: '100.0'
architectureWithholdingFlickr: '73.2'
architectureWithholdingFlickrMean: '74.4'
architectureWithholdingFlickrStd: '2.2'
architectureWithholdingLOne: '20.8'
architectureWithholdingLOneMean: '20.8'
architectureWithholdingLOneStd: '0.1'
architectureWithholdingVGG: '45.5'
architectureWithholdingVGGMean: '44.3'
architectureWithholdingVGGStd: '1.5'
architectureWithholdingthree: '72.4'
architectureWithholdingthreeMean: '74.2'
architectureWithholdingthreeStd: '1.3'
datasetWithholdingFlickr: '0.0'
datasetWithholdingFlickrMean: '0.0'
datasetWithholdingFlickrStd: '0.0'
datasetWithholdingLOne: '25.6'
datasetWithholdingLOneMean: '26.1'
datasetWithholdingLOneStd: '0.4'
datasetWithholdingRCAN: '36.6'
datasetWithholdingRCANMean: '36.2'
datasetWithholdingRCANStd: '1.0'
datasetWithholdingSwinIR: '34.3'
datasetWithholdingSwinIRMean: '33.0'
datasetWithholdingSwinIRStd: '1.4'
datasetWithholdingVGG: '31.5'
datasetWithholdingVGGMean: '31.9'
datasetWithholdingVGGStd: '0.3'
fourXarchitectureWithholdingFlickr: '81.5'
fourXarchitectureWithholdingLOne: '20.8'
fourXarchitectureWithholdingVGG: '52.9'
fourXarchitectureWithholdingthree: '73.5'
fourXdatasetWithholdingFlickr: '0.0'
fourXdatasetWithholdingLOne: '25.3'
fourXdatasetWithholdingRCAN: '45.5'
fourXdatasetWithholdingSwinIR: '33.9'
fourXdatasetWithholdingVGG: '35.0'
fourXlossWithholdingFlickr: '99.1'
fourXlossWithholdingRCAN: '92.2'
fourXlossWithholdingSwinIR: '92.5'
fourXlossWithholdingthree: '98.3'
fourXscaleWithholdingFlickr: '100.0'
fourXscaleWithholdingLOne: '4.2'
fourXscaleWithholdingRCAN: '99.2'
fourXscaleWithholdingSwinIR: '98.3'
fourXscaleWithholdingVGG: '99.0'
fourXscaleWithholdingthree: '100.0'
lOnearchitectureWithholdingFlickr: '73.0'
lOnearchitectureWithholdingLOne: '20.8'
lOnearchitectureWithholdingthree: '76.0'
lOnedatasetWithholdingFlickr: '0.0'
lOnedatasetWithholdingLOne: '25.6'
lOnedatasetWithholdingRCAN: '34.9'
lOnedatasetWithholdingSwinIR: '29.4'
lOnelossWithholdingFlickr: '100.0'
lOnelossWithholdingRCAN: '100.0'
lOnelossWithholdingSwinIR: '100.0'
lOnelossWithholdingthree: '100.0'
lOnescaleWithholdingFlickr: '100.0'
lOnescaleWithholdingLOne: '52.1'
lOnescaleWithholdingRCAN: '100.0'
lOnescaleWithholdingSwinIR: '100.0'
lOnescaleWithholdingthree: '100.0'
lossWithholdingFlickr: '98.7'
lossWithholdingFlickrMean: '98.4'
lossWithholdingFlickrStd: '0.2'
lossWithholdingRCAN: '94.9'
lossWithholdingRCANMean: '95.5'
lossWithholdingRCANStd: '0.5'
lossWithholdingSwinIR: '94.3'
lossWithholdingSwinIRMean: '94.3'
lossWithholdingSwinIRStd: '0.2'
lossWithholdingthree: '98.8'
lossWithholdingthreeMean: '98.6'
lossWithholdingthreeStd: '0.2'
scaleWithholdingFlickr: '100.0'
scaleWithholdingFlickrMean: '100.0'
scaleWithholdingFlickrStd: '0.0'
scaleWithholdingLOne: '52.1'
scaleWithholdingLOneMean: '51.5'
scaleWithholdingLOneStd: '0.5'
scaleWithholdingRCAN: '99.4'
scaleWithholdingRCANMean: '99.4'
scaleWithholdingRCANStd: '0.0'
scaleWithholdingSwinIR: '99.2'
scaleWithholdingSwinIRMean: '99.6'
scaleWithholdingSwinIRStd: '0.3'
scaleWithholdingVGG: '99.4'
scaleWithholdingVGGMean: '98.9'
scaleWithholdingVGGStd: '0.4'
scaleWithholdingthree: '100.0'
scaleWithholdingthreeMean: '100.0'
scaleWithholdingthreeStd: '0.0'
twoXarchitectureWithholdingFlickr: '64.9'
twoXarchitectureWithholdingLOne: '20.9'
twoXarchitectureWithholdingVGG: '38.1'
twoXarchitectureWithholdingthree: '71.4'
twoXdatasetWithholdingFlickr: '0.0'
twoXdatasetWithholdingLOne: '25.9'
twoXdatasetWithholdingRCAN: '27.8'
twoXdatasetWithholdingSwinIR: '34.7'
twoXdatasetWithholdingVGG: '28.0'
twoXlossWithholdingFlickr: '98.3'
twoXlossWithholdingRCAN: '97.6'
twoXlossWithholdingSwinIR: '96.2'
twoXlossWithholdingthree: '99.3'
twoXscaleWithholdingFlickr: '99.9'
twoXscaleWithholdingLOne: '100.0'
twoXscaleWithholdingRCAN: '99.6'
twoXscaleWithholdingSwinIR: '100.0'
twoXscaleWithholdingVGG: '99.9'
twoXscaleWithholdingthree: '100.0'
