classifier:
  type: FEN
  name: PRNU_SISR_all_models
  train:
    num_epochs: 2
    learning_rate: 0.0001

training_dataset:
  name: SISR_all_models_train
  type: SISR
  random_crop: false
  include_pretrained: true
  include_custom_trained: true

evaluation_datasets:
  -
    name: SISR_all_models_test
    type: SISR
    random_crop: false
    include_pretrained: true
    include_custom_trained: true