classifier:
  type: CNN
  name: Xception_CNN_SISR_all_models
  cnn:
    type: 'Xception'
  train:
    num_pretrain_epochs: 1
    num_full_train_epochs: 1
    batch_size: 16
    learning_rate_start: 0.0005
    learning_rate_end: 0.000004

training_dataset:
  type: SISR
  name: SISR_all_models_train
  random_crop: false
  include_pretrained: true
  include_custom_trained: true
  data_retention: 0.01

validation_dataset:
  name: SISR_all_models_val
  type: SISR
  random_crop: false
  include_pretrained: true
  include_custom_trained: true
  data_retention: 0.01

evaluation_datasets:
  -
    name: SISR_all_models_test
    type: SISR
    random_crop: false
    include_pretrained: true
    include_custom_trained: true
    data_retention: 0.01