classifier:
  type: CNN
  name: EfficientNet_CNN_SISR_all_models
  pretrained_path: classification/classifiers/experiments/CNN/EfficientNet_CNN_SISR_all_models_OLD/model_best.pt
  cnn:
    type: 'EfficientNet'
  train:
    num_pretrain_epochs: 3
    num_full_train_epochs: 3
    batch_size: 16
    learning_rate_start: 0.0005
    learning_rate_end: 0.000004

training_dataset:
  type: SISR
  name: SISR_all_models_train
  random_crop: true
  include_pretrained: true
  include_custom_trained: true

validation_dataset:
  name: SISR_all_models_val
  type: SISR
  random_crop: false
  include_pretrained: true
  include_custom_trained: true

evaluation_datasets:
  -
    name: SISR_all_models_test
    type: SISR
    random_crop: false
    include_pretrained: true
    include_custom_trained: true
